import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color Palette
        "inverse-primary": "#d2bbff",
        "tertiary": "#4e4e55",
        "secondary-container": "#d9b5ff",
        "secondary": "#6f5092",
        "on-tertiary-fixed": "#1a1b21",
        "tertiary-fixed": "#e3e1e9",
        "outline-variant": "#ccc3d8",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "primary": "#630ed4",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "outline": "#7b7487",
        "on-surface-variant": "#4a4455",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-primary-container": "#ede0ff",
        "surface": "#faf8ff",
        "secondary-fixed-dim": "#dbb8ff",
        "tertiary-container": "#66666d",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed-dim": "#c7c5cd",
        "surface-bright": "#faf8ff",
        "on-primary-fixed": "#25005a",
        "inverse-surface": "#283044",
        "surface-tint": "#732ee4",
        "primary-fixed": "#eaddff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#46464d",
        "on-secondary-fixed": "#29074a",
        "on-background": "#131b2e",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#e6e5ed",
        "background": "#faf8ff",
        "on-secondary-fixed-variant": "#573878",
        "on-secondary-container": "#614283",
        "surface-container-highest": "#dae2fd",
        "primary-fixed-dim": "#d2bbff",
        "secondary-fixed": "#efdbff",
        "surface-variant": "#dae2fd",
        "primary-container": "#7c3aed",

        // Dashboard/auth design tokens (src/app/tokens.css)
        "accent": "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-light": "var(--color-accent-light)",
        "accent-soft": "var(--color-accent-soft)",
        "foreground": "var(--color-text-primary)",
        "border": "var(--color-border)",
        "danger": "var(--color-danger)",
        "danger-bg": "var(--color-danger-bg)",
        "success": "var(--color-success)",
        "success-bg": "var(--color-success-bg)",
        "warning": "var(--color-warning)",
        "warning-bg": "var(--color-warning-bg)",
        "info": "var(--color-info)",
        "info-bg": "var(--color-info-bg)",
      },
      spacing: {
        "unit-xs": "4px",
        "unit-lg": "24px",
        "gutter": "24px",
        "unit-md": "16px",
        "margin-mobile": "20px",
        "unit-xl": "48px",
        "unit-sm": "8px",
        "container-max": "1280px",
        "margin-desktop": "48px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline-xl": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}

export default config
